import { CalendarDays, CheckCircle2, Hash, Search, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import api from '../api'
import { Alert, Card } from './ui'
import { buttonStyles, inputClass } from './uiStyles'

function BookingForm({ equipment, onBooked }) {
  const [form, setForm] = useState({ startDate: '', expectedReturnDate: '', quantity: 1 })
  const [availability, setAvailability] = useState(null)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const updateField = (event) => { setForm({ ...form, [event.target.name]: event.target.value }); setAvailability(null); setMessage(''); setError('') }
  const checkAvailability = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { const { data } = await api.get(`/equipment/${equipment._id}/availability`, { params: { startDate: form.startDate, endDate: form.expectedReturnDate } }); setAvailability(data.equipment) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to check availability') } }
  const bookEquipment = async () => { setBusy(true); setError(''); setMessage(''); try { const { data } = await api.post('/rentals', { equipmentId: equipment._id, quantity: Number(form.quantity), startDate: form.startDate, expectedReturnDate: form.expectedReturnDate }); setMessage(`Reservation confirmed. Deposit: ₹${data.rental.depositAmount}`); setAvailability(null); onBooked?.() } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to reserve equipment') } finally { setBusy(false) } }
  const available = availability?.availableQuantity || 0
  return <Card className="p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-blue-600"><CalendarDays size={19} /></span><div><h2 className="text-lg font-bold text-slate-900">Reserve equipment</h2><p className="mt-1 text-sm text-slate-500">Choose your dates and quantity.</p></div></div><form onSubmit={checkAvailability} className="mt-6 space-y-4"><label className="block text-sm font-medium text-slate-700">Quantity<div className="relative"><Hash size={16} className="absolute left-3 top-3 text-slate-400" /><input required min="1" type="number" name="quantity" value={form.quantity} onChange={updateField} className={`${inputClass} pl-9`} /></div></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Start date<div className="relative"><CalendarDays size={16} className="absolute left-3 top-3 text-slate-400" /><input required type="date" name="startDate" value={form.startDate} onChange={updateField} className={`${inputClass} pl-9`} /></div></label><label className="block text-sm font-medium text-slate-700">Return date<div className="relative"><CalendarDays size={16} className="absolute left-3 top-3 text-slate-400" /><input required type="date" name="expectedReturnDate" value={form.expectedReturnDate} onChange={updateField} className={`${inputClass} pl-9`} /></div></label></div><button type="submit" className={`${buttonStyles.primary} w-full`}><Search size={16} />Check availability</button></form>{availability && <div className={`mt-5 rounded-lg border p-4 ${available >= Number(form.quantity) ? 'border-emerald-200 bg-emerald-50' : 'border-red-200 bg-red-50'}`}><div className="flex items-start gap-3">{available >= Number(form.quantity) ? <CheckCircle2 size={18} className="mt-0.5 text-emerald-600" /> : <ShieldCheck size={18} className="mt-0.5 text-red-600" />}<div><p className={`text-sm font-semibold ${available >= Number(form.quantity) ? 'text-emerald-700' : 'text-red-700'}`}>{available >= Number(form.quantity) ? `${available} units available` : 'No units available for the selected dates.'}</p><p className="mt-1 text-xs text-slate-600">Deposit: ₹{Number(form.quantity) * equipment.depositPerUnit}</p></div></div>{available >= Number(form.quantity) && <button type="button" onClick={bookEquipment} disabled={busy} className={`${buttonStyles.secondary} mt-4 w-full`}>{busy ? 'Reserving...' : 'Reserve equipment'}</button>}</div>}{message && <div className="mt-4"><Alert type="success">{message}</Alert></div>}{error && <div className="mt-4"><Alert>{error}</Alert></div>}</Card>
}

export default BookingForm
